In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('Street_Tree_List-2022-01-30_FILTERED.csv')

In [8]:
data

TreeID    qLegalStatus  \
0      200311  DPW Maintained   
1       10425  DPW Maintained   
2       43163  DPW Maintained   
3      188921  DPW Maintained   
4         643  DPW Maintained   
...       ...             ...   
37113  141243  DPW Maintained   
37114  203553  DPW Maintained   
37115   61778  DPW Maintained   
37116  190242  DPW Maintained   
37117  192307  DPW Maintained   

                                                qSpecies  \
0      Liquidambar styraciflua 'Rotundiloba' :: Round...   
1           Schinus terebinthifolius :: Brazilian Pepper   
2                 Acacia melanoxylon :: Blackwood Acacia   
3              Callistemon citrinus :: Lemon Bottlebrush   
4                     Ficus microcarpa :: Chinese Banyan   
...                                                  ...   
37113          Magnolia grandiflora :: Southern Magnolia   
37114               Agonis flexuosa :: Peppermint Willow   
37115                Eriobotrya deflexa :: Bronze Loquat   
37116  Ficus microcarpa nitida 'Green Gem' :: Indian ...   
37117                            Fraxinus spp :: Ash Spp   

                   qAddress  SiteOrder                       qSiteInfo  \
0              300 Spear St        9.0      Sidewalk: Curb side : Yard   
1            1419 Haight St        2.0    Sidewalk: Curb side : Cutout   
2            222 Madison St        1.0    Sidewalk: Curb side : Cutout   
3              2001 25th St       16.0  Sidewalk: Property side : Yard   
4              3224 24th St        1.0    Sidewalk: Curb side : Cutout   
...                     ...        ...                             ...   
37113   31 COMMONWEALTH AVE        1.0      Sidewalk: Curb side : Yard   
37114         259 Faxon Ave        1.0    Sidewalk: Curb side : Cutout   
37115          2219 24th St        1.0    Sidewalk: Curb side : Cutout   
37116  60 New Montgomery St        3.0       Sidewalk: Curb side : Pot   
37117        100 De Haro St        1.0    Sidewalk: Curb side : Cutout   

      qCaretaker     PlantDate  DBH   PlotSize   Latitude   Longitude  
0        Private           NaN    5        NaN  37.789193 -122.390006  
1            DPW           NaN   90        3x3  37.770094 -122.445693  
2        Private  7/11/00 0:00    8        NaN  37.726036 -122.422690  
3        Private           NaN    6  Width 8ft  37.751955 -122.399482  
4        Private           NaN   18        3x3  37.752398 -122.416772  
...          ...           ...  ...        ...        ...         ...  
37113    Private           NaN   10  Width 0ft  37.785434 -122.455909  
37114    Private           NaN    2  Width 3ft  37.719278 -122.460296  
37115    Private  1/22/85 0:00   13        NaN  37.753203 -122.401882  
37116    Private           NaN    2  Width 3ft  37.788459 -122.401854  
37117    Private           NaN   12  Width 4ft  37.767303 -122.401956  

[37118 rows x 12 columns]

In [6]:
yrdata = data[data['PlantDate'].notnull()]

In [48]:
yrdata['year']

2        2000
10       2010
13       2015
14       2008
18       2017
         ... 
37093    2008
37099    1998
37102    2018
37111    1989
37115    1985
Name: year, Length: 9337, dtype: object

In [7]:
yrdata

TreeID    qLegalStatus  \
2       43163  DPW Maintained   
10      94792  DPW Maintained   
13      29149  DPW Maintained   
14      82688  DPW Maintained   
18      30326  DPW Maintained   
...       ...             ...   
37093   90144  DPW Maintained   
37099   38541  DPW Maintained   
37102    1457  DPW Maintained   
37111   54849  DPW Maintained   
37115   61778  DPW Maintained   

                                                qSpecies           qAddress  \
2                 Acacia melanoxylon :: Blackwood Acacia     222 Madison St   
10                             Maytenus boaria :: Mayten        2 Laurel St   
13                 Lophostemon confertus :: Brisbane Box      301X Jones St   
14               Crataegus laevigata :: English Hawthorn      1875 38th Ave   
18                 Tristaniopsis laurina :: Swamp Myrtle    946 Capitol Ave   
...                                                  ...                ...   
37093  Tristaniopsis laurina 'Elegant' :: Small-leaf ...      338 Balboa St   
37099          Magnolia grandiflora :: Southern Magnolia   1543 Jennings St   
37102             Pittosporum undulatum :: Victorian Box  160 Arguello Blvd   
37111                   Prunus cerasifera :: Cherry Plum      2076 Grove St   
37115                Eriobotrya deflexa :: Bronze Loquat       2219 24th St   

       SiteOrder                     qSiteInfo qCaretaker       PlantDate  \
2            1.0  Sidewalk: Curb side : Cutout    Private    7/11/00 0:00   
10           4.0  Sidewalk: Curb side : Cutout    Private    11/8/10 0:00   
13           1.0  Sidewalk: Curb side : Cutout        DPW    6/13/15 0:00   
14           1.0  Sidewalk: Curb side : Cutout    Private    6/30/08 0:00   
18           1.0  Sidewalk: Curb side : Cutout    Private  10/13/17 11:13   
...          ...                           ...        ...             ...   
37093        1.0  Sidewalk: Curb side : Cutout        DPW    2/11/08 0:00   
37099        1.0  Sidewalk: Curb side : Cutout    Private    9/17/98 0:00   
37102        1.0  Sidewalk: Curb side : Cutout        DPW    3/29/18 0:00   
37111        1.0  Sidewalk: Curb side : Cutout    Private     4/3/89 0:00   
37115        1.0  Sidewalk: Curb side : Cutout    Private    1/22/85 0:00   

       DBH PlotSize   Latitude   Longitude  
2        8      NaN  37.726036 -122.422690  
10      13      NaN  37.790988 -122.450849  
13       3      3x3  37.783950 -122.412686  
14       2      3x3  37.751978 -122.496833  
18       3      NaN  37.719069 -122.459124  
...    ...      ...        ...         ...  
37093    3      3x3  37.777378 -122.462528  
37099    7      NaN  37.730299 -122.385654  
37102    3      3X3  37.787257 -122.459200  
37111    8      NaN  37.774373 -122.450701  
37115   13      NaN  37.753203 -122.401882  

[9337 rows x 12 columns]

In [9]:
yrdata['PlantDate'] = pd.to_datetime(yrdata['PlantDate'])

<ipython-input-9-1a3aa96dfacd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrdata['PlantDate'] = pd.to_datetime(yrdata['PlantDate'])


In [63]:
yrdata['year'] = yrdata['PlantDate'].apply(lambda x: x.year)
yrdata = yrdata[yrdata['year'] <=2023]

<ipython-input-63-264d8d611c64>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrdata['year'] = yrdata['PlantDate'].apply(lambda x: x.year)


In [64]:
yrdata['year'].unique()

array([2000, 2010, 2015, 2008, 2017, 2014, 2002, 2018, 2012, 2007, 1976,
       2021, 2016, 2019, 2006, 1992, 2009, 1995, 1996, 1993, 1974, 1986,
       1973, 1994, 2001, 2003, 1999, 1997, 2004, 2005, 2013, 2011, 1998,
       1985, 1987, 1991, 1982, 2020, 1990, 1983, 1980, 1989, 1984, 1988,
       1981, 1979, 1977, 1978, 2022, 1975])

In [65]:
yrdata['decade'] = '{}0 - {}9'.format(str(yrdata['year'])[:3],str(yrdata['year'])[:3])

<ipython-input-65-fd56c5008e4e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrdata['decade'] = '{}0 - {}9'.format(str(yrdata['year'])[:3],str(yrdata['year'])[:3])


In [66]:
yrdata['decade'] = yrdata['year'].apply(lambda x: '{}0 - {}9'.format(str(x)[:3],str(x)[:3]))

<ipython-input-66-4dd7a921a3ea>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrdata['decade'] = yrdata['year'].apply(lambda x: '{}0 - {}9'.format(str(x)[:3],str(x)[:3]))


In [67]:
yrdata['year'].unique()

array([2000, 2010, 2015, 2008, 2017, 2014, 2002, 2018, 2012, 2007, 1976,
       2021, 2016, 2019, 2006, 1992, 2009, 1995, 1996, 1993, 1974, 1986,
       1973, 1994, 2001, 2003, 1999, 1997, 2004, 2005, 2013, 2011, 1998,
       1985, 1987, 1991, 1982, 2020, 1990, 1983, 1980, 1989, 1984, 1988,
       1981, 1979, 1977, 1978, 2022, 1975])

In [15]:
test = set([entry.split(' ')[0] for entry in yrdata['qSpecies'].unique()])
len(test)

116

In [68]:
yrdata['PrimaryCaretaker'] = yrdata['qCaretaker'].apply(lambda x: 'Others' if (x!='DPW' and x!='Private') else x)

<ipython-input-68-fe71249864a0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yrdata['PrimaryCaretaker'] = yrdata['qCaretaker'].apply(lambda x: 'Others' if (x!='DPW' and x!='Private') else x)


In [72]:
yrdata.groupby(['decade','PrimaryCaretaker']).count()['TreeID'].to_csv('letmetry.csv')

In [24]:
yrdata['PlotSize'].unique()

array([nan, '3x3', '5x5', '3X3', '4X4', 'Width 4ft', 'Width 3ft', '4x6',
       '2X2', 'Width 2ft', '2X3', '3X4', 'Width 0ft', '4x4', '2x2', 'M',
       '3x6', '3X6', '4', '5x6', '5', 'Width 6ft', 'Width 10ft', '6x6',
       '2', '6x4', '5x7', '20', '8M', '4.5x6', '6x9', '9x12', 'Width 8ft',
       '3X10', '10', '12x17', '3x30', '9x3', '3x5', '5x10', '14M',
       'Width 5ft', '3x2', '9x9', '6x8', '3', '2x3', '3x12', '3x4',
       '6x300', '4x8', '10x20', '3x100', '3x14', '3X5', '6x12', '6x3',
       '3x9', 'CUT', '5X5', '2x4', '8', '1x2', '7x3', '1x4', '6', '6X6',
       '8x6', '6x10', '4.5x5.5', '7x4', '.5x1', '6x5', '5x9', '15', '9x6',
       '4x3', 'TR20', '12x31', '9', '3x10', '4x5', '10x10', '3c3', '4x10',
       '6x18', '5.5x6.5', '3x8', '3X70', '3x25', '18x3', '4X6', '5x4',
       'TR', '6x7', '2.9x31.8', '3X2', '5X8', '2x9', '7x7', '15x280',
       '8x45', '5x3', 'ex3', '3x20', '2.5x3', '8x8', '10x4', '6x11',
       '2x5', '4.5x5', '10x6', '4.5X4.5', '8x100', '10X10', '3X3PL',

In [71]:
yrdata['decade'].unique()

array(['2000 - 2009', '2010 - 2019', '1970 - 1979', '2020 - 2029',
       '1990 - 1999', '1980 - 1989'], dtype=object)

In [70]:
yrdata.to_csv('preprocessed_year_data.csv')